package vistas.main;

import javax.swing.JFrame;
import utilidades.CambiaPanel;
import vistas.modulos.Home;


public class Menu extends javax.swing.JFrame {

    boolean menuActived = true;
    boolean opEntradas = false;
    boolean opSalidas = false;
    
    public Menu() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        new CambiaPanel(this.body, new Home());
        this.btnCompraEntradas.setVisible(false);
        this.btnDevoEntradas.setVisible(false);
        this.btnVentaSalidas.setVisible(false);
        this.btnDevoSalidas.setVisible(false);
    }

    
    public void iniciar(){
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        aside = new javax.swing.JPanel();
        modulos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        rSButtonIcon_new3 = new newscomponents.RSButtonIcon_new();
        btnHome = new newscomponents.RSButtonIcon_new();
        btnSalidas = new newscomponents.RSButtonIcon_new();
        btnDevoSalidas = new newscomponents.RSButtonIcon_new();
        btnVentaSalidas = new newscomponents.RSButtonIcon_new();
        btnCompraEntradas = new newscomponents.RSButtonIcon_new();
        btnEntradas = new newscomponents.RSButtonIcon_new();
        btnDevoEntradas = new newscomponents.RSButtonIcon_new();
        rSButtonIcon_new9 = new newscomponents.RSButtonIcon_new();
        header = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnMenu = new RSMaterialComponent.RSButtonIconOne();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aside.setBackground(new java.awt.Color(42, 53, 66));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 2);
        flowLayout1.setAlignOnBaseline(true);
        aside.setLayout(flowLayout1);

        modulos.setOpaque(false);
        modulos.setLayout(new java.awt.GridBagLayout());

        jLabel13.setBackground(new java.awt.Color(37, 46, 57));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("MENÚ");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jLabel13.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 202;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        modulos.add(jLabel13, gridBagConstraints);

        rSButtonIcon_new3.setBackground(new java.awt.Color(42, 53, 66));
        rSButtonIcon_new3.setText("Reporte Kardex");
        rSButtonIcon_new3.setBackgroundHover(new java.awt.Color(61, 137, 248));
        rSButtonIcon_new3.setFocusPainted(false);
        rSButtonIcon_new3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonIcon_new3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonIcon_new3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOTE);
        rSButtonIcon_new3.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(rSButtonIcon_new3, gridBagConstraints);

        btnHome.setBackground(new java.awt.Color(241, 123, 55));
        btnHome.setText("Inicio");
        btnHome.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnHome.setFocusPainted(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHome.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnHome.setVerifyInputWhenFocusTarget(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnHome, gridBagConstraints);

        btnSalidas.setBackground(new java.awt.Color(42, 53, 66));
        btnSalidas.setText("Salidas");
        btnSalidas.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnSalidas.setFocusPainted(false);
        btnSalidas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnSalidas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnSalidas.setVerifyInputWhenFocusTarget(false);
        btnSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnSalidas, gridBagConstraints);

        btnDevoSalidas.setBackground(new java.awt.Color(255, 255, 255));
        btnDevoSalidas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        btnDevoSalidas.setForeground(new java.awt.Color(51, 51, 51));
        btnDevoSalidas.setText("Devolución");
        btnDevoSalidas.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnDevoSalidas.setFocusPainted(false);
        btnDevoSalidas.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        btnDevoSalidas.setForegroundIcon(new java.awt.Color(42, 53, 66));
        btnDevoSalidas.setForegroundText(new java.awt.Color(42, 53, 66));
        btnDevoSalidas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDevoSalidas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDevoSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT_RETURN);
        btnDevoSalidas.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnDevoSalidas, gridBagConstraints);

        btnVentaSalidas.setBackground(new java.awt.Color(255, 255, 255));
        btnVentaSalidas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        btnVentaSalidas.setForeground(new java.awt.Color(51, 51, 51));
        btnVentaSalidas.setText("Venta");
        btnVentaSalidas.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnVentaSalidas.setFocusPainted(false);
        btnVentaSalidas.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        btnVentaSalidas.setForegroundIcon(new java.awt.Color(42, 53, 66));
        btnVentaSalidas.setForegroundText(new java.awt.Color(42, 53, 66));
        btnVentaSalidas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnVentaSalidas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentaSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_SHOPPING_CART);
        btnVentaSalidas.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnVentaSalidas, gridBagConstraints);

        btnCompraEntradas.setBackground(new java.awt.Color(255, 255, 255));
        btnCompraEntradas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        btnCompraEntradas.setForeground(new java.awt.Color(51, 51, 51));
        btnCompraEntradas.setText("Compra");
        btnCompraEntradas.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnCompraEntradas.setFocusPainted(false);
        btnCompraEntradas.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        btnCompraEntradas.setForegroundIcon(new java.awt.Color(42, 53, 66));
        btnCompraEntradas.setForegroundText(new java.awt.Color(42, 53, 66));
        btnCompraEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCompraEntradas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCompraEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_SHOPPING_CART);
        btnCompraEntradas.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnCompraEntradas, gridBagConstraints);

        btnEntradas.setBackground(new java.awt.Color(42, 53, 66));
        btnEntradas.setText("Entradas");
        btnEntradas.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnEntradas.setFocusPainted(false);
        btnEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEntradas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btnEntradas.setVerifyInputWhenFocusTarget(false);
        btnEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnEntradas, gridBagConstraints);

        btnDevoEntradas.setBackground(new java.awt.Color(255, 255, 255));
        btnDevoEntradas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 25, 1, 1));
        btnDevoEntradas.setForeground(new java.awt.Color(51, 51, 51));
        btnDevoEntradas.setText("Devolución");
        btnDevoEntradas.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnDevoEntradas.setFocusPainted(false);
        btnDevoEntradas.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        btnDevoEntradas.setForegroundIcon(new java.awt.Color(42, 53, 66));
        btnDevoEntradas.setForegroundText(new java.awt.Color(42, 53, 66));
        btnDevoEntradas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDevoEntradas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDevoEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ASSIGNMENT_RETURN);
        btnDevoEntradas.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(btnDevoEntradas, gridBagConstraints);

        rSButtonIcon_new9.setBackground(new java.awt.Color(42, 53, 66));
        rSButtonIcon_new9.setText("Productos");
        rSButtonIcon_new9.setBackgroundHover(new java.awt.Color(61, 137, 248));
        rSButtonIcon_new9.setFocusPainted(false);
        rSButtonIcon_new9.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        rSButtonIcon_new9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonIcon_new9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.INBOX);
        rSButtonIcon_new9.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        modulos.add(rSButtonIcon_new9, gridBagConstraints);

        aside.add(modulos);

        getContentPane().add(aside, java.awt.BorderLayout.LINE_START);

        header.setBackground(new java.awt.Color(61, 137, 248));
        header.setLayout(new java.awt.GridBagLayout());

        jLabel10.setBackground(new java.awt.Color(61, 137, 248));
        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sistema de Control de Inventario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.weightx = 10.0;
        header.add(jLabel10, gridBagConstraints);

        btnMenu.setBackground(new java.awt.Color(61, 137, 248));
        btnMenu.setBackgroundHover(new java.awt.Color(61, 137, 248));
        btnMenu.setFocusPainted(false);
        btnMenu.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MENU);
        btnMenu.setSizeIcon(25.0F);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        header.add(btnMenu, gridBagConstraints);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(236, 240, 245));
        body.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        body.setForeground(new java.awt.Color(204, 204, 204));
        body.setLayout(new javax.swing.BoxLayout(body, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        if(menuActived == true){
            menuActived = false;
            this.aside.setVisible(false);
        }else{
            menuActived = true;
            this.aside.setVisible(true);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasActionPerformed
        if(opEntradas == false){
            opEntradas = true;
            this.btnCompraEntradas.setVisible(true);
            this.btnDevoEntradas.setVisible(true);
            this.btnEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXPAND_MORE);
        }else{
            opEntradas = false;
            this.btnCompraEntradas.setVisible(false);
            this.btnDevoEntradas.setVisible(false);
            this.btnEntradas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        }
    }//GEN-LAST:event_btnEntradasActionPerformed

    private void btnSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidasActionPerformed
        if(opSalidas == false){
            opSalidas = true;
            this.btnVentaSalidas.setVisible(true);
            this.btnDevoSalidas.setVisible(true);
            this.btnSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXPAND_MORE);
        }else{
            opSalidas = false;
            this.btnVentaSalidas.setVisible(false);
            this.btnDevoSalidas.setVisible(false);
            this.btnSalidas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        }
    }//GEN-LAST:event_btnSalidasActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        new CambiaPanel(this.body, new Home());
    }//GEN-LAST:event_btnHomeActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel aside;
    public javax.swing.JPanel body;
    private newscomponents.RSButtonIcon_new btnCompraEntradas;
    private newscomponents.RSButtonIcon_new btnDevoEntradas;
    private newscomponents.RSButtonIcon_new btnDevoSalidas;
    private newscomponents.RSButtonIcon_new btnEntradas;
    private newscomponents.RSButtonIcon_new btnHome;
    private RSMaterialComponent.RSButtonIconOne btnMenu;
    private newscomponents.RSButtonIcon_new btnSalidas;
    private newscomponents.RSButtonIcon_new btnVentaSalidas;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JPanel modulos;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new3;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new9;
    // End of variables declaration//GEN-END:variables
}
